import test from 'node:test';
import assert from 'node:assert/strict';
import { eodWorkbookAttachment, readZip } from '../lib/eod-xlsx.mjs';
const layout = { Interior: 7, Exterior: 7, Grading: 5 };
const lines = Object.entries(layout).flatMap(([section, n]) => Array.from({ length: n }, (_, i) => ({ section, line: i + 1, description: '', qty: 0, rate: 0 })));
Object.assign(lines[0], { description: 'Skilled Labor <8 HR>', qty: 16, rate: 65 });
Object.assign(lines[8], { description: 'Full Truck Load', qty: 2, rate: 375 });
test('EOD sheet produces the filled Job Costing workbook as a base64 .xlsx', () => {
  const file = eodWorkbookAttachment({ jobName: 'Acme - 123 Main', date: '2026-09-23', markupPercent: 20, lines });
  assert.equal(file.mimeType, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  assert.match(file.fileName, /^EOD Sheet - Acme - 123 Main - 2026-09-23\.xlsx$/);
  const entries = readZip(Buffer.from(file.data, 'base64'));
  assert.equal(entries.length, 20);
  const sheet = entries.find(e => e.name === 'xl/worksheets/sheet1.xml').data.toString('utf8');
  const cell = ref => sheet.match(new RegExp(`<c r="${ref}"[^>]*?(?:/>|>[\\s\\S]*?</c>)`))[0];
  assert.match(cell('C2'), /Acme - 123 Main/);
  assert.match(cell('C3'), /09\/23\/2026/);
  assert.match(cell('B8'), /Skilled Labor &lt;8 HR&gt;/);
  assert.match(cell('E8'), /<f[^>]*>C8\*D8<\/f><v>1040<\/v>/);
  assert.match(cell('E20'), /<v>750<\/v>/);
  assert.match(cell('E37'), /<v>1790<\/v>/);
  assert.match(cell('E38'), /<v>0.2<\/v>/);
  assert.match(cell('E39'), /<v>2148<\/v>/);
});
